Repository Hello-Kitchen/Back-End, pull requests merged in 2024-10, with the labels that each got.

#46 feat: add new route '/status/:idFoodOrdered' for updated status of th…
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/shared/interfaces/restaurant.interface.ts
Labels: 💥 New feature

#47 Release v1.0.1
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/shared/interfaces/restaurant.interface.ts
Labels: 👨‍🦯 Ignore for release

#53 fix: add field name and quantity
  src/db/db.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: 🪲 Bug

#52 fix: add 'id' field into json return on route 'api/:idRestaurant/orde…
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: 🪲 Bug

#57 feat: add all documentation into all file
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/db/db.ts
  src/main.ts
  src/modules/details/details.controller.ts
  src/modules/details/details.module.ts
  src/modules/details/details.service.ts
  src/modules/details/interfaces/details.interface.ts
  src/modules/food/food.controller.ts
  src/modules/food/food.module.ts
  src/modules/food/food.service.ts
  src/modules/food/interfaces/food.interface.ts
  src/modules/food_category/food_category.controller.ts
  src/modules/food_category/food_category.module.ts
  src/modules/food_category/food_category.service.ts
  src/modules/food_category/interfaces/food_category.interface.ts
  src/modules/ingredient/ingredient.controller.ts
  src/modules/ingredient/ingredient.module.ts
  src/modules/ingredient/ingredient.service.ts
  src/modules/ingredient/interfaces/ingredient.interface.ts
  src/modules/login/login.controller.ts
  src/modules/login/login.module.ts
  src/modules/login/login.service.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/orders.service.ts
  src/modules/permission/permission.controller.ts
  src/modules/permission/permission.module.ts
  src/modules/permission/permission.service.ts
  src/modules/pos/pos.controller.ts
  src/modules/pos/pos.module.ts
  src/modules/pos/pos.service.ts
  src/modules/restaurants/restaurants.controller.ts
  src/modules/restaurants/restaurants.module.ts
  src/modules/restaurants/restaurants.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/shared/interfaces/counter.interface.ts
  src/shared/interfaces/order.interface.ts
  src/shared/interfaces/restaurant.interface.ts
Labels: 📚 Documentation

#58 fix: change return error code HTTP for all route
  src/modules/details/details.controller.ts
  src/modules/food/food.controller.ts
  src/modules/food_category/food_category.controller.ts
  src/modules/ingredient/ingredient.controller.ts
  src/modules/orders/orders.controller.ts
  src/modules/permission/permission.controller.ts
  src/modules/permission/permission.service.ts
  src/modules/pos/pos.controller.ts
  src/modules/restaurants/restaurants.controller.ts
  src/modules/users/users.controller.ts
Labels: ☀️ Enhancement

#60 feat: add authentification with jwt and protected all route apart rou…
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/details/details.controller.ts
  src/modules/food/food.controller.ts
  src/modules/food_category/food_category.controller.ts
  src/modules/ingredient/ingredient.controller.ts
  src/modules/login/jwt.strategy.ts
  src/modules/login/login.controller.ts
  src/modules/login/login.module.ts
  src/modules/login/login.service.ts
  src/modules/orders/orders.controller.ts
  src/modules/permission/permission.controller.ts
  src/modules/pos/pos.controller.ts
  src/modules/restaurants/restaurants.controller.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  src/shared/guards/jwt-auth.guard.ts
Labels: ☀️ Enhancement

#65 orders/next/ API route
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: 💥 New feature
