Repository Hello-Kitchen/Back-End, pull requests merged in 2024-06, with the labels that each got.

#3 feat: init repo for back end with node js and framework express
  .gitignore
  package-lock.json
  package.json
  server.js
Labels: 👨‍🦯 Ignore for release

#5 feat:CRUD pour toutes les collections de la DB de base
  package-lock.json
  package.json
  routes/api/detail.js
  routes/api/food.js
  routes/api/foodCategory.js
  routes/api/foodOrdered.js
  routes/api/ingredient.js
  routes/api/keys.apiRoutes.js
  routes/api/order.js
  routes/api/user.js
  routes/apiRoutes.js
  server.js
Labels: 👨‍🦯 Ignore for release

#6 fix: connection base de donnee via un .env
  .gitignore
  README.md
  config/config.js
  routes/api/detail.js
  routes/api/food.js
  routes/api/foodCategory.js
  routes/api/foodOrdered.js
  routes/api/ingredient.js
  routes/api/keys.apiRoutes.js
  routes/api/order.js
  routes/api/user.js
  routes/apiRoutes.js
Labels: 🪲 Bug

#8 feat: CRUD API restaurant
  routes/api/keys.apiRoutes.js
  routes/api/restaurant.js
  routes/apiRoutes.js
Labels: 👨‍🦯 Ignore for release

#15 feat: Ajout route pour login
  config/config.js
  package-lock.json
  package.json
  routes/api/login.js
  routes/apiRoutes.js
  server.js
Labels: 💥 New feature
