Repository Hello-Kitchen/Back-End, pull requests merged in 2025-01, with the labels that each got.

#83 Route get Order servie
  src/modules/orders/DTO/orders.dto.ts
  src/modules/orders/orders.controller.spec.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/modules/orders/pipe/status.pipe.ts
Labels: 💥 New feature

#89 Add foodcategory params
  src/modules/food/food.controller.spec.ts
  src/modules/food/food.controller.ts
  src/modules/food/pipe/foodCategory.pipe.ts
Labels: 💥 New feature

#90 doc: Hosted documentation in backend
  docs/swagger.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.service.ts
  src/main.ts
  temp
Labels: 📚 Documentation

#92 Param 'useCase' into route get Food by ID
  docs/swagger.json
  src/modules/food/food.controller.spec.ts
  src/modules/food/food.controller.ts
  src/modules/food/food.service.ts
  src/modules/food/pipe/useCase.pipe.ts
Labels: 💥 New feature

#96 add filter time with the param 'served'
  src/modules/orders/orders.controller.ts
Labels: 🪲 Bug

#98 Fix Param ready and sort by time
  src/modules/orders/orders.service.ts
Labels: 🪲 Bug
